<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CurrencySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table("currencies")->insert(["country_name" => "United Arab Emirates", "country_code" => "AE", "currency" => "AED",]);
        DB::table("currencies")->insert(["country_name" => "Armenia", "country_code" => "AM", "currency" => "AMD",]);
        DB::table("currencies")->insert(["country_name" => "Angola", "country_code" => "AO", "currency" => "AOA",]);
        DB::table("currencies")->insert(["country_name" => "Argentina", "country_code" => "AR", "currency" => "ARS",]);
        DB::table("currencies")->insert(["country_name" => "Australia", "country_code" => "AU", "currency" => "AUD",]);
        DB::table("currencies")->insert(["country_name" => "Austria", "country_code" => "AT", "currency" => "EUR",]);
        DB::table("currencies")->insert(["country_name" => "Aruba", "country_code" => "AW", "currency" => "AWG",]);
        DB::table("currencies")->insert(["country_name" => "Azerbaijan", "country_code" => "AZ", "currency" => "AZN",]);
        DB::table("currencies")->insert(["country_name" => "Bosnia and Herzegovina", "country_code" => "BA", "currency" => "BAM",]);
        DB::table("currencies")->insert(["country_name" => "Barbados", "country_code" => "BB", "currency" => "BBD",]);
        DB::table("currencies")->insert(["country_name" => "Bangladesh", "country_code" => "BD", "currency" => "BDT",]);
        DB::table("currencies")->insert(["country_name" => "Bulgaria", "country_code" => "BG", "currency" => "BGN",]);
        DB::table("currencies")->insert(["country_name" => "Burundi", "country_code" => "BI", "currency" => "BIF",]);
        DB::table("currencies")->insert(["country_name" => "Bermuda", "country_code" => "BM", "currency" => "BMD",]);
        DB::table("currencies")->insert(["country_name" => "Brunei Darussalam", "country_code" => "BN", "currency" => "BND",]);
        DB::table("currencies")->insert(["country_name" => "Bolivia, Plurinational State of", "country_code" => "BO", "currency" => "BOB",]);
        DB::table("currencies")->insert(["country_name" => "Brazil", "country_code" => "BR", "currency" => "BRL",]);
        DB::table("currencies")->insert(["country_name" => "Bahamas", "country_code" => "BS", "currency" => "BSD",]);
        DB::table("currencies")->insert(["country_name" => "Belgium", "country_code" => "BE", "currency" => "EUR",]);
        DB::table("currencies")->insert(["country_name" => "Lithuania", "country_code" => "LT", "currency" => "EUR",]);
        DB::table("currencies")->insert(["country_name" => "Luxembourg", "country_code" => "LU", "currency" => "EUR",]);
        DB::table("currencies")->insert(["country_name" => "Netherlands", "country_code" => "NL", "currency" => "EUR",]);
        DB::table("currencies")->insert(["country_name" => "Sweden", "country_code" => "SE", "currency" => "SEK",]);
        DB::table("currencies")->insert(["country_name" => "Singapore", "country_code" => "SG", "currency" => "SGD",]);
        DB::table("currencies")->insert(["country_name" => "Thailand", "country_code" => "TH", "currency" => "THB",]);
        DB::table("currencies")->insert(["country_name" => "United States", "country_code" => "US", "currency" => "USD", "symbol" => "$",]);
        DB::table("currencies")->insert(["country_name" => "Canada", "country_code" => "CA", "currency" => "CAD",]);
        DB::table("currencies")->insert(["country_name" => "Liechtenstein", "country_code" => "LI", "currency" => "CHF",]);
        DB::table("currencies")->insert(["country_name" => "CHFSwitzerland", "country_code" => "CH", "currency" => "CHF",]);
        DB::table("currencies")->insert(["country_name" => "Czech Republic", "country_code" => "CZ", "currency" => "CZK",]);
        DB::table("currencies")->insert(["country_name" => "Mexico", "country_code" => "MX", "currency" => "MXN",]);
        DB::table("currencies")->insert(["country_name" => "Malaysia", "country_code" => "MY", "currency" => "MYR",]);
        DB::table("currencies")->insert(["country_name" => "Norway", "country_code" => "NO", "currency" => "NOK",]);
        DB::table("currencies")->insert(["country_name" => "New Zealand", "country_code" => "NZ", "currency" => "NZD",]);
        DB::table("currencies")->insert(["country_name" => "Poland", "country_code" => "PL", "currency" => "PLN",]);
        DB::table("currencies")->insert(["country_name" => "Romania", "country_code" => "RO", "currency" => "RON",]);
        DB::table("currencies")->insert(["country_name" => "Denmark", "country_code" => "DK", "currency" => "DKK",]);
        DB::table("currencies")->insert(["country_name" => "Cyprus", "country_code" => "CY", "currency" => "EUR", "symbol" => "€",]);
        DB::table("currencies")->insert(["country_name" => "Estonia", "country_code" => "EE", "currency" => "EUR", "symbol" => "€",]);
        DB::table("currencies")->insert(["country_name" => "Finland", "country_code" => "FI", "currency" => "EUR", "symbol" => "€",]);
        DB::table("currencies")->insert(["country_name" => "France", "country_code" => "FR", "currency" => "EUR", "symbol" => "€",]);
        DB::table("currencies")->insert(["country_name" => "Germany", "country_code" => "DE", "currency" => "EUR", "symbol" => "€",]);
        DB::table("currencies")->insert(["country_name" => "Greece", "country_code" => "GR", "currency" => "EUR", "symbol" => "€",]);
        DB::table("currencies")->insert(["country_name" => "Ireland", "country_code" => "IE", "currency" => "EUR", "symbol" => "€",]);
        DB::table("currencies")->insert(["country_name" => "Italy", "country_code" => "IT", "currency" => "EUR", "symbol" => "€",]);
        DB::table("currencies")->insert(["country_name" => "Latvia", "country_code" => "LV", "currency" => "EUR", "symbol" => "€",]);
        DB::table("currencies")->insert(["country_name" => "Malta", "country_code" => "MT", "currency" => "EUR", "symbol" => "€",]);
        DB::table("currencies")->insert(["country_name" => "Portugal", "country_code" => "PT", "currency" => "EUR", "symbol" => "€",]);
        DB::table("currencies")->insert(["country_name" => "Slovakia", "country_code" => "SK", "currency" => "EUR", "symbol" => "€",]);
        DB::table("currencies")->insert(["country_name" => "Slovenia", "country_code" => "SI", "currency" => "EUR", "symbol" => "€",]);
        DB::table("currencies")->insert(["country_name" => "Spain", "country_code" => "ES", "currency" => "EUR", "symbol" => "€",]);
        DB::table("currencies")->insert(["country_name" => "United Kingdom", "country_code" => "GB", "currency" => "GBP", "symbol" => "£",]);
        DB::table("currencies")->insert(["country_name" => "Gibraltar", "country_code" => "GI", "currency" => "GIP",]);
        DB::table("currencies")->insert(["country_name" => "Hong Kong", "country_code" => "HK", "currency" => "HKD",]);
        DB::table("currencies")->insert(["country_name" => "Croatia", "country_code" => "HR", "currency" => "HRK",]);
        DB::table("currencies")->insert(["country_name" => "Hungary", "country_code" => "HUF", "currency" => "HUF",]);
        DB::table("currencies")->insert(["country_name" => "Indonesia", "country_code" => "ID", "currency" => "IDR",]);
        DB::table("currencies")->insert(["country_name" => "India", "country_code" => "IN", "currency" => "INR",]);
        // DB::table("currencies")->insert(["country_name" => "Japan", "country_code" => "JP", "currency" => "JPY",]);
        // DB::table("currencies")->insert(["country_name" => "", "country_code" => "", "currency" => "KES",]);
        // DB::table("currencies")->insert(["country_name" => "", "country_code" => "", "currency" => "KGS",]);
        // DB::table("currencies")->insert(["country_name" => "", "country_code" => "", "currency" => "KHR",]);
        // DB::table("currencies")->insert(["country_name" => "", "country_code" => "", "currency" => "KMF",]);
        // DB::table("currencies")->insert(["country_name" => "", "country_code" => "", "currency" => "KRW",]);
        // DB::table("currencies")->insert(["country_name" => "", "country_code" => "", "currency" => "KYD",]);
        // DB::table("currencies")->insert(["country_name" => "", "country_code" => "", "currency" => "KZT",]);
        // DB::table("currencies")->insert(["country_name" => "", "country_code" => "", "currency" => "LAK",]);
        // DB::table("currencies")->insert(["country_name" => "", "country_code" => "", "currency" => "LBP",]);
        // DB::table("currencies")->insert(["country_name" => "", "country_code" => "", "currency" => "LKR",]);
        // DB::table("currencies")->insert(["country_name" => "", "country_code" => "", "currency" => "LRD",]);
        // DB::table("currencies")->insert(["country_name" => "", "country_code" => "", "currency" => "LSL",]);
        // DB::table("currencies")->insert(["country_name" => "", "country_code" => "", "currency" => "LTL",]);
        // DB::table("currencies")->insert(["country_name" => "", "country_code" => "", "currency" => "MAD",]);
        // DB::table("currencies")->insert(["country_name" => "", "country_code" => "", "currency" => "MDL",]);
        // DB::table("currencies")->insert(["country_name" => "", "country_code" => "", "currency" => "MKD",]);
        // DB::table("currencies")->insert(["country_name" => "", "country_code" => "", "currency" => "MNT",]);
        // DB::table("currencies")->insert(["country_name" => "", "country_code" => "", "currency" => "MOP",]);
        // DB::table("currencies")->insert(["country_name" => "", "country_code" => "", "currency" => "MUR",]);
        // DB::table("currencies")->insert(["country_name" => "", "country_code" => "", "currency" => "MVR",]);
        // DB::table("currencies")->insert(["country_name" => "", "country_code" => "", "currency" => "MWK",]);
        // DB::table("currencies")->insert(["country_name" => "", "country_code" => "", "currency" => "MZN",]);
        // DB::table("currencies")->insert(["country_name" => "", "country_code" => "", "currency" => "NAD",]);
        // DB::table("currencies")->insert(["country_name" => "", "country_code" => "", "currency" => "NGN",]);
        // DB::table("currencies")->insert(["country_name" => "", "country_code" => "", "currency" => "NIO",]);
        // DB::table("currencies")->insert(["country_name" => "", "country_code" => "", "currency" => "NPR",]);
        // DB::table("currencies")->insert(["country_name" => "", "country_code" => "", "currency" => "PAB",]);
        // DB::table("currencies")->insert(["country_name" => "", "country_code" => "", "currency" => "PEN",]);
        // DB::table("currencies")->insert(["country_name" => "", "country_code" => "", "currency" => "PGK",]);
        // DB::table("currencies")->insert(["country_name" => "", "country_code" => "", "currency" => "PHP",]);
        // DB::table("currencies")->insert(["country_name" => "", "country_code" => "", "currency" => "PKR",]);
        // DB::table("currencies")->insert(["country_name" => "", "country_code" => "", "currency" => "PYG",]);
        // DB::table("currencies")->insert(["country_name" => "", "country_code" => "", "currency" => "QAR",]);
        // DB::table("currencies")->insert(["country_name" => "", "country_code" => "", "currency" => "RSD",]);
        // DB::table("currencies")->insert(["country_name" => "", "country_code" => "", "currency" => "RUB",]);
        // DB::table("currencies")->insert(["country_name" => "", "country_code" => "", "currency" => "RWF",]);
        // DB::table("currencies")->insert(["country_name" => "", "country_code" => "", "currency" => "SAR",]);
        // DB::table("currencies")->insert(["country_name" => "", "country_code" => "", "currency" => "SBD",]);
        // DB::table("currencies")->insert(["country_name" => "", "country_code" => "", "currency" => "SCR",]);
        // DB::table("currencies")->insert(["country_name" => "", "country_code" => "", "currency" => "SHP",]);
        // DB::table("currencies")->insert(["country_name" => "", "country_code" => "", "currency" => "SLL",]);
        // DB::table("currencies")->insert(["country_name" => "", "country_code" => "", "currency" => "SOS",]);
        // DB::table("currencies")->insert(["country_name" => "", "country_code" => "", "currency" => "SRD",]);
        // DB::table("currencies")->insert(["country_name" => "", "country_code" => "", "currency" => "STD",]);
        // DB::table("currencies")->insert(["country_name" => "", "country_code" => "", "currency" => "SVC",]);
        // DB::table("currencies")->insert(["country_name" => "", "country_code" => "", "currency" => "SYP",]);
        // DB::table("currencies")->insert(["country_name" => "", "country_code" => "", "currency" => "SZL",]);
        // DB::table("currencies")->insert(["country_name" => "", "country_code" => "", "currency" => "TJS",]);
        // DB::table("currencies")->insert(["country_name" => "", "country_code" => "", "currency" => "TOP",]);
        // DB::table("currencies")->insert(["country_name" => "", "country_code" => "", "currency" => "TRY",]);
        // DB::table("currencies")->insert(["country_name" => "", "country_code" => "", "currency" => "TTD",]);
        // DB::table("currencies")->insert(["country_name" => "", "country_code" => "", "currency" => "TWD",]);
        // DB::table("currencies")->insert(["country_name" => "", "country_code" => "", "currency" => "TZS",]);
        // DB::table("currencies")->insert(["country_name" => "", "country_code" => "", "currency" => "UAH",]);
        // DB::table("currencies")->insert(["country_name" => "", "country_code" => "", "currency" => "UGX",]);
        // DB::table("currencies")->insert(["country_name" => "", "country_code" => "", "currency" => "UYU",]);
        // DB::table("currencies")->insert(["country_name" => "", "country_code" => "", "currency" => "UZS",]);
        // DB::table("currencies")->insert(["country_name" => "", "country_code" => "", "currency" => "VES",]);
        // DB::table("currencies")->insert(["country_name" => "", "country_code" => "", "currency" => "VND",]);
        // DB::table("currencies")->insert(["country_name" => "", "country_code" => "", "currency" => "VUV",]);
        // DB::table("currencies")->insert(["country_name" => "", "country_code" => "", "currency" => "WST",]);
        // DB::table("currencies")->insert(["country_name" => "", "country_code" => "", "currency" => "XAF",]);
        // DB::table("currencies")->insert(["country_name" => "", "country_code" => "", "currency" => "XCD",]);
        // DB::table("currencies")->insert(["country_name" => "", "country_code" => "", "currency" => "XOF",]);
        // DB::table("currencies")->insert(["country_name" => "", "country_code" => "", "currency" => "XPF",]);
        // DB::table("currencies")->insert(["country_name" => "", "country_code" => "", "currency" => "YER",]);
        // DB::table("currencies")->insert(["country_name" => "", "country_code" => "", "currency" => "ZAR",]);
        // DB::table("currencies")->insert(["country_name" => "", "country_code" => "", "currency" => "ZMK",]);
        // DB::table("currencies")->insert(["country_name" => "", "country_code" => "", "currency" => "ZWD",]);
        // DB::table("currencies")->insert(["country_name" => "", "country_code" => "", "currency" => "CLP",]);
        // DB::table("currencies")->insert(["country_name" => "", "country_code" => "", "currency" => "CNY",]);
        // DB::table("currencies")->insert(["country_name" => "", "country_code" => "", "currency" => "COP",]);
        // DB::table("currencies")->insert(["country_name" => "", "country_code" => "", "currency" => "CRC",]);
        // DB::table("currencies")->insert(["country_name" => "", "country_code" => "", "currency" => "CVE",]);
        // DB::table("currencies")->insert(["country_name" => "", "country_code" => "", "currency" => "BWP",]);
        // DB::table("currencies")->insert(["country_name" => "", "country_code" => "", "currency" => "BYN",]);
        // DB::table("currencies")->insert(["country_name" => "", "country_code" => "", "currency" => "BZD",]);
        // DB::table("currencies")->insert(["country_name" => "", "country_code" => "", "currency" => "DOP",]);
        // DB::table("currencies")->insert(["country_name" => "", "country_code" => "", "currency" => "DZD",]);
        // DB::table("currencies")->insert(["country_name" => "", "country_code" => "", "currency" => "EGP",]);
        // DB::table("currencies")->insert(["country_name" => "", "country_code" => "", "currency" => "ETB",]);
        // DB::table("currencies")->insert(["country_name" => "", "country_code" => "", "currency" => "GMD",]);
        // DB::table("currencies")->insert(["country_name" => "", "country_code" => "", "currency" => "GNF",]);
        // DB::table("currencies")->insert(["country_name" => "", "country_code" => "", "currency" => "GTQ",]);
        // DB::table("currencies")->insert(["country_name" => "", "country_code" => "", "currency" => "GYD",]);
        // DB::table("currencies")->insert(["country_name" => "", "country_code" => "", "currency" => "GEL",]);
        // DB::table("currencies")->insert(["country_name" => "", "country_code" => "", "currency" => "GHS",]);
        // DB::table("currencies")->insert(["country_name" => "", "country_code" => "", "currency" => "FJD",]);
        // DB::table("currencies")->insert(["country_name" => "", "country_code" => "", "currency" => "FKP",]);
        // DB::table("currencies")->insert(["country_name" => "", "country_code" => "", "currency" => "DJF",]);
        // DB::table("currencies")->insert(["country_name" => "", "country_code" => "", "currency" => "HNL",]);
        // DB::table("currencies")->insert(["country_name" => "", "country_code" => "", "currency" => "HTG",]);
        // DB::table("currencies")->insert(["country_name" => "", "country_code" => "", "currency" => "ILS",]);
        // DB::table("currencies")->insert(["country_name" => "", "country_code" => "", "currency" => "ISK",]);
        // DB::table("currencies")->insert(["country_name" => "", "country_code" => "", "currency" => "JMD",]);
    }
}
